#!/usr/bin/env bash
# Build a single-file, self-extracting installer for distribution.
#
#   ./make_installer.sh
#     -> laser_control_installer.sh   (hand this ONE file to the other PC)
#
# The output is a shell script with a base64 tarball appended after a marker
# line. Running it unpacks into a target directory and runs install.sh there,
# so the recipient needs no git, no scp of a directory tree, and no knowledge
# of what is inside. base64 (rather than a raw tar) keeps the payload
# 7-bit-clean so it survives being emailed, pasted, or served over HTTP by
# something that would otherwise mangle binary bytes.

set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUT="$HERE/laser_control_installer.sh"
STAGE="$(mktemp -d)"
trap 'rm -rf "$STAGE"' EXIT

# Files that make up the distributable. Deliberately explicit: a glob would
# sweep in venv/, log/, __pycache__ and the previous installer.
FILES=(
    laser_driver.py
    laser_cli.py
    laser_gui.py
    run_gui.sh
    install.sh
    requirements.txt
    99-tamadenshi.rules
    laser_env.sh.example
    README.md
    설치방법.txt
)

echo "Staging files..."
mkdir -p "$STAGE/laser_control"
for f in "${FILES[@]}"; do
    if [[ ! -e "$HERE/$f" ]]; then
        echo "  MISSING: $f" >&2
        exit 1
    fi
    cp "$HERE/$f" "$STAGE/laser_control/"
    echo "  + $f"
done
chmod +x "$STAGE/laser_control/"{install.sh,run_gui.sh,laser_cli.py,laser_gui.py}

echo "Packing..."
tar -czf "$STAGE/payload.tgz" -C "$STAGE" laser_control

# --- installer stub -------------------------------------------------------
cat > "$OUT" <<'STUB_EOF'
#!/usr/bin/env bash
# Self-extracting installer for the Tamadenshi laser control software.
#
#   ./laser_control_installer.sh                 install to ~/laser_control
#   ./laser_control_installer.sh --dir /opt/las  install elsewhere
#   ./laser_control_installer.sh --extract-only  unpack, do not run install.sh
#
# Generated by make_installer.sh -- do not edit by hand.

set -euo pipefail

TARGET="$HOME/laser_control"
EXTRACT_ONLY=0
PASSTHRU=()

while [[ $# -gt 0 ]]; do
    case "$1" in
        --dir) TARGET="$2"; shift 2 ;;
        --extract-only) EXTRACT_ONLY=1; shift ;;
        --no-sudo|--no-gui) PASSTHRU+=("$1"); shift ;;
        -h|--help) sed -n '2,9p' "$0"; exit 0 ;;
        *) echo "Unknown option: $1" >&2; exit 1 ;;
    esac
done

echo "=================================================="
echo " Tamadenshi Laser Control -- installer"
echo "=================================================="
echo " Target directory: $TARGET"
echo

for tool in tar base64 python3; do
    command -v "$tool" >/dev/null 2>&1 || {
        echo "Required tool not found: $tool" >&2; exit 1; }
done

# Never silently overwrite an existing install -- venv/, log/ and
# laser_gui_config.json may hold the operator's data.
if [[ -e "$TARGET" ]]; then
    echo "'$TARGET' already exists."
    read -rp "Overwrite the program files in it? (log/ and venv/ are kept) [y/N] " ans
    [[ "${ans,,}" == y || "${ans,,}" == yes ]] || { echo "Aborted."; exit 1; }
fi

mkdir -p "$TARGET"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

echo "Extracting..."
ARCHIVE_LINE=$(awk '/^__PAYLOAD_BELOW__$/ {print NR + 1; exit 0}' "$0")
tail -n +"$ARCHIVE_LINE" "$0" | base64 -d | tar -xz -C "$TMP"
cp -r "$TMP/laser_control/." "$TARGET/"
chmod +x "$TARGET"/{install.sh,run_gui.sh,laser_cli.py,laser_gui.py} 2>/dev/null || true
echo "  unpacked into $TARGET"
echo

if [[ $EXTRACT_ONLY -eq 1 ]]; then
    echo "Extract-only requested. Finish with:"
    echo "    cd $TARGET && ./install.sh"
    exit 0
fi

echo "Running setup..."
echo
cd "$TARGET"
exec ./install.sh "${PASSTHRU[@]+"${PASSTHRU[@]}"}"

__PAYLOAD_BELOW__
STUB_EOF

base64 "$STAGE/payload.tgz" >> "$OUT"
chmod +x "$OUT"

SIZE=$(du -h "$OUT" | cut -f1)
echo
echo "Built: $OUT  ($SIZE)"
echo
echo "Distribute that single file. On the target PC:"
echo "    chmod +x laser_control_installer.sh"
echo "    ./laser_control_installer.sh"
